"""empty message

Revision ID: eb27c0637c60
Revises: 
Create Date: 2024-04-02 17:59:43.833860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb27c0637c60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheer',
    sa.Column('cheer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('cheer_id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date2', sa.DateTime(), nullable=True),
    sa.Column('time', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('player', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('plan')
    op.drop_table('cheer')
    # ### end Alembic commands ###
